package com.example.xaviernara.newmindapp;

import android.os.Bundle;
import android.app.Activity;
import android.text.Html;
import android.text.method.ScrollingMovementMethod;
import android.widget.EditText;
import android.widget.TextView;

public class BeliefsActivity extends Activity {

    TextView beliefsText,visionText,missionText;

    String htmlText1 = "<h2>What We Believe</h2>\n" +
            "We believe in the Bible.  The Bible is the Logos, the inspired written Word of God.  Holy men were led by the Spirit to write and record the scriptures.  We accept the Full Gospel, the Old and New Testament.  (II Timothy 3;16, I Thessalonians 2:13, II Peter 1:21)\n" +
            "We believe in the Trinity: One God manifested in three person (Genesis 1:1-3, 26, I John 5:8, Matthew 28:19)\n" +
            "God the Father, the Head of the Deity (John 14:28, John 16:28)\n" +
            "God the Son, the Word made flesh (John 1:1-5, 14, 5:17-18, Philippians 2:5-6)\n" +
            "God the Holy Spirit, the Comforter, the Parakletos (Genesis 1:2, John 14:16-17, 16:13-14, Act 5:3-4)\n" +
            "We believe in the creation.  We believe that God is the creator of all things whether in heaven or earth and all things that exists.  Man is a created being made in the image and likeness of God. (Genesis 1:1, Acts 17:24, Colossians 1:16-17)\n" +
            "We believe in the fall and redemption of Man.  Adam because of his disobedience brought death – spiritual separation from God.  He caused sin to enter into the world, but by Christ the second Adam, dying once and for all paying the penalty for sin, thus redeeming man back to God. (Genesis 3:6-7, II Corinthians 15:22)\n" +
            "We believe in everlasting / eternal life.  Anyone who confesses with their mouth Lord Jesus and believe in their heart that God raised Jesus from the dead shall be saved and have everlasting life and they become a new creature. (Romans 10:9-10, John 3:16-17, II Corinthian 5:17)\n" +
            "We believe that man must be born again.  Because of man’s sin, it brought death, spiritual separation from God, but upon him receiving Christ he became born again, regenerated by the Spirit and Water. (John 3:5-7, 16)\n" +
            "We believe in Water Baptism.  Baptism is subsequent to salvation.  We believe that baptism is the total immersion of the body, and is essential to all believers.  It identifies with the death, burial and resurrection of Christ. (Matthew 28:19, Romans 6:3-5, Colossians 2:12)\n" +
            "We believe in the Baptism of the Holy Spirit.  Being  filled with the Holy Spirit is a gift from God to benefit the believer.  It is the promise given to man to empower as a believer.  This experience is made evident by man speaking in other tongues as the Spirit gives utterance (an outside manifestation of an inside work). (Acts 1:5-8, 2:2-4)\n" +
            "We believe in the Gifts of the Spirit.  We believe that all 9 gifts of the Spirit are still in full operation today.  (I Corinthians 12:1-11)\n" +
            "We believe in the 5 fold ministry gifts.  We embrace the offices of the Apostles, Prophets, Pastor, Evangelists and Teachers.  These offices were established by God for the advancing of the kingdom of God. (Eph. 5:22)\n" +
            "We believe in Holiness.  We believe that after a believer has received Christ as Lord and Savior that there should be change that man no longer lives under the bondage of sin, but has the power to live free from it. (II Corinthians 7:1, Hebrews 12:14, Romans 8:2)\n" +
            "We believe in Godliness, We believe that the believer should live a God conscious reverential awe of God. A lifestyle that acknowledges weighs their actions against God as an everyday\n" +
            "We believe in the free moving of the Holy Spirit.  We believe that  Holy Spirit governs and control our worship service to minister to the needs in the church.  So we humbly yield to Him, realizing that when he is present, we are liberated. (II Corinthians 3:17)\n" +
            "We believe in the blessed hope (The Rapture).  We believe that Christ’ coming is imminent upon his return the dead in Christ shall be raised first and those who remain shall be caught up and meet the Lord in the air and will be with the Lord forever.  This experience will take place before the tribulation. (I Thessalonians 4:16-17)\n" +
            "\"";


    String htmlText2 = "<h2>MISSION</h2>\n" +
            "\n" +
            "\n" +
            "Being led by Holy Spirit, we will proclaim the Full Gospel by evangelizing the world, compelling the unsaved to come into the saving knowledge of Jesus. We will “Renew the Mind” of the total man, body, soul and spirit, through Kingdom concepts. We will carry out our assignment: Reconcile, Relate, Restore, Renew, Reinforce, Release and Rejoice. We will establish this concept by equipping the believer, using task specific methods through strategic teaching and disciplined faith in God’s Word.\n" +
            "\n" +
            "\n" +
            "\n" +
            "Through the promoting our I.C.C.E. concept: Integrity, Character, Compassion and Excellence. We will develop an atmosphere whereby the believer will thrive and reach monument success. Our culture geared toward wholesome fellowship, authentic worship and dynamic teaching of the Word of God maximizing potential and purpose is expected and encouraged.\n" +
            "\n" +
            "\n" +
            "\n" +
            "Through lives sacrificed to God, we will allow him to use us as He pleases, “Advancing His Kingdom” by promoting an all inclusive ministry where all gifts and talents are embraced and given the opportunity to flourish. We will create tomorrow’s leaders, today.";


    String htmlText3 = "<h2>VISION</h2>\n" +
            "The Vision of New Mind Kingdom Ministries is to minister to the Whole man, Body, Soul and Spirit through various ministries set in place to focus on specific needs via systematic teachings from the Word of God.\n" +
            "\n" +
            "We will accomplish this by promoting an I.C.C.E (Integrity Character Compassion Excellence) Culture.\n" +
            "\n" +
            "Integrity- presenting things honest, establishing a base of trust whereby the believer can be sure.\n" +
            "Character-exemplifying Christ in our lives even while people aren’t watching, being who we say that we are.\n" +
            "Compassion- genuine love and concern exemplifying that Christ like passion.\n" +
            "Excellence-having an eye giving to detail, always doing our best in all things so that God may be glorified.\n" +
            "This will be an environment free from special interest groups.\n" +
            "\n" +
            "\n" +
            "Our objective is to help guide the believer to discover their Purpose and Destiny. This mandate is displayed in our 7Rs concept. It is a check and balance system set in place to edify the believer:\n" +
            "\n" +
            "Reconcile- bring man back to God to discover their purpose.\n" +
            "Relate- being a believable example, relating with people from where they are and from whence the come.\n" +
            "Restore- working with them to get them healthy, building them up in their faith by the Word of God, offering healing for the Body soul and spirit.\n" +
            "Renew- Transforming their minds to have a complete understanding of what God’s plan for their lives. We are changing the “church mentality to Kingdom (all inclusive), a mentality enriching them through the message of hope, faith and salvation.\n" +
            "Reinforce- Through systematic strategic teaching of the Word, offering information, instruction and insight, relative to their vocation where they’ve been called.\n" +
            "Release- Our main goal is to get the believer to the point of release, pushing them out of the nest, encouraging them to go forth and perform God’s purpose for their lives.\n" +
            "Rejoice- rejoicing with when they are carrying out their God given purpose, seeing them excel in their profession.\n" +
            "We will truly “Renew the Mind” through ministries, outreach shelter for battered and abused, rehabilitation center for substance dependency, assisting former convicts to reconnect to society, a social center, a safe haven for youth and young adults, offering tutoring, assistance in obtaining G.E.D, building a family support system aiding in enhancing spousal role, parenting skills, and how to run a efficient and productive households.\n" +
            "\n" +
            "\n" +
            "We will create a Pathway to Purpose so that the believer will be in a culture that is purpose driven!";



    @Override
    protected void onCreate(Bundle savedInstanceState) {

        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_beilefs);

        beliefsText = findViewById(R.id.beliefs);
        beliefsText.setText(Html.fromHtml(htmlText1,Html.FROM_HTML_MODE_COMPACT));
        beliefsText.setMovementMethod(new ScrollingMovementMethod());

        visionText = findViewById(R.id.vision);
        visionText.setText(Html.fromHtml(htmlText2,Html.FROM_HTML_MODE_COMPACT));
        visionText.setMovementMethod(new ScrollingMovementMethod());

        missionText = findViewById(R.id.mission);
        missionText.setText(Html.fromHtml(htmlText3,Html.FROM_HTML_MODE_COMPACT));
        missionText.setMovementMethod(new ScrollingMovementMethod());

    }
}
